server:
  port: 9011
  address: '[::]'
spring:
  application:
    name: user-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/tisser
    username: postgres
    password: 277353
  neo4j:
    uri: bolt://localhost:7687/tisser
    authentication:
      username: neo4j
      password: 6154277353
  data:
    mongodb:
      database: tisser
      uri: mongodb://localhost:27017/tisser
      authentication-database: mongo